title = "Leonardo Andreta de Castro"
author = "Leonardo Andreta de Castro"
description = "Physicist and software developer"

contents_dir = "./contents"
data_dir = "./data"
templates_dir = "./templates"

[data]
contact = "contact.toml"

[[contents]]
file = "about.md"
title = "About"
