base_url = "https://www.leoadec.com"

title = "Leonardo Andreta de Castro"
author = "Leonardo Andreta de Castro"
description = "Physicist and software developer"

output_dir = "_site"
ignored_content = ["*.yaml"]

compile_sass = true
generate_sitemap = false
generate_robots_txt = false
