title = "Leonardo Andreta de Castro"
author = "Leonardo Andreta de Castro"
description = "Physicist and software developer"

contents_dir = "./contents"
data_dir = "./data"
templates_dir = "./templates"

[data]
authors = "authors.toml"
contact = "contact.toml"
conferences = "conferences.toml"
degrees = "degrees.toml"
grants = "grants.toml"
jobs = "jobs.toml"
locations = "locations.toml"
papers = "papers.toml"
posters = "posters.toml"
talks = "talks.toml"
theses = "theses.toml"

[[contents]]
file = "about.md"
title = "About"
