name: Hakyll

on:
  push:
    branches: ["hakyll"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Restore Stack cache
      uses: actions/cache/restore@v4
      with:
        path: .stack/
        key: ${{ runner.os }}-hakyll-stack 
    - name: Install Stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Build with Stack
      run: stack build
    - name: Save Stack cache
      uses: actions/cache/save@v4
      with:
        path: .stack/
        key: ${{ runner.os }}-hakyll-stack 
